/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ProtobufAny } from '../models/protobuf-any';
export interface RpcStatus {
  code?: number;
  details?: Array<ProtobufAny>;
  message?: string;
}
