/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Note is the resource managed by Notesd.
 */
export interface V1Note {

  /**
   * account_id scopes the resource to a tenant; the repository filters every
   * query by it (set from the request's tenant context — see server/main.go).
   */
  accountId?: string;

  /**
   * AIP-148: soft-delete timestamp; set by Delete, cleared by Undelete.
   */
  deleteTime?: string;
  description?: string;

  /**
   * display_name is a human-friendly label; indexed for lookup.
   */
  displayName?: string;

  /**
   * AIP-154 ETag: framework-managed; stamped on every write, surfaced on read.
   */
  etag?: string;
  id?: string;

  /**
   * name is the AIP-122 resource name, e.g. "notes/abc123".
   */
  name?: string;
}
