/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { V1Note } from '../models/v-1-note';
export interface V1ListNotesResponse {
  nextPageToken?: string;
  notes?: Array<V1Note>;
}
