/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { ProtobufAny } from './models/protobuf-any';
export type { RpcStatus } from './models/rpc-status';
export type { V1DeleteNoteResponse } from './models/v-1-delete-note-response';
export type { V1ListNotesResponse } from './models/v-1-list-notes-response';
export type { V1Note } from './models/v-1-note';
