/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { V1ListNotesResponse } from '../../models/v-1-list-notes-response';

export interface NoteServiceListNotes$Params {
  pageSize?: number;
  pageToken?: string;

/**
 * AIP-148: include soft-deleted resources when true.
 */
  showDeleted?: boolean;
}

export function noteServiceListNotes(http: HttpClient, rootUrl: string, params?: NoteServiceListNotes$Params, context?: HttpContext): Observable<StrictHttpResponse<V1ListNotesResponse>> {
  const rb = new RequestBuilder(rootUrl, noteServiceListNotes.PATH, 'get');
  if (params) {
    rb.query('pageSize', params.pageSize, {});
    rb.query('pageToken', params.pageToken, {});
    rb.query('showDeleted', params.showDeleted, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<V1ListNotesResponse>;
    })
  );
}

noteServiceListNotes.PATH = '/v1/notes';
