/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { V1Note } from '../../models/v-1-note';

export interface NoteServiceGetNote$Params {
  id: string;

/**
 * AIP-157: fields to return; empty means all fields.
 */
  readMask?: string;
}

export function noteServiceGetNote(http: HttpClient, rootUrl: string, params: NoteServiceGetNote$Params, context?: HttpContext): Observable<StrictHttpResponse<V1Note>> {
  const rb = new RequestBuilder(rootUrl, noteServiceGetNote.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
    rb.query('readMask', params.readMask, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<V1Note>;
    })
  );
}

noteServiceGetNote.PATH = '/v1/notes/{id}';
