/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { V1DeleteNoteResponse } from '../../models/v-1-delete-note-response';

export interface NoteServiceDeleteNote$Params {
  id: string;
}

export function noteServiceDeleteNote(http: HttpClient, rootUrl: string, params: NoteServiceDeleteNote$Params, context?: HttpContext): Observable<StrictHttpResponse<V1DeleteNoteResponse>> {
  const rb = new RequestBuilder(rootUrl, noteServiceDeleteNote.PATH, 'delete');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<V1DeleteNoteResponse>;
    })
  );
}

noteServiceDeleteNote.PATH = '/v1/notes/{id}';
