/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { V1Note } from '../../models/v-1-note';

export interface NoteServiceUpdateNote$Params {
  'note.id': string;
  updateMask?: Array<string>;
      body: {

/**
 * account_id scopes the resource to a tenant; the repository filters every
 * query by it (set from the request's tenant context — see server/main.go).
 */
'accountId'?: string;

/**
 * AIP-148: soft-delete timestamp; set by Delete, cleared by Undelete.
 */
'deleteTime'?: string;
'description'?: string;

/**
 * display_name is a human-friendly label; indexed for lookup.
 */
'displayName'?: string;

/**
 * AIP-154 ETag: framework-managed; stamped on every write, surfaced on read.
 */
'etag'?: string;

/**
 * name is the AIP-122 resource name, e.g. "notes/abc123".
 */
'name'?: string;
}
}

export function noteServiceUpdateNote(http: HttpClient, rootUrl: string, params: NoteServiceUpdateNote$Params, context?: HttpContext): Observable<StrictHttpResponse<V1Note>> {
  const rb = new RequestBuilder(rootUrl, noteServiceUpdateNote.PATH, 'patch');
  if (params) {
    rb.path('note.id', params['note.id'], {});
    rb.query('updateMask', params.updateMask, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<V1Note>;
    })
  );
}

noteServiceUpdateNote.PATH = '/v1/notes/{note.id}';
