/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { V1Note } from '../../models/v-1-note';

export interface NoteServiceCreateNote$Params {
      body: V1Note
}

export function noteServiceCreateNote(http: HttpClient, rootUrl: string, params: NoteServiceCreateNote$Params, context?: HttpContext): Observable<StrictHttpResponse<V1Note>> {
  const rb = new RequestBuilder(rootUrl, noteServiceCreateNote.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<V1Note>;
    })
  );
}

noteServiceCreateNote.PATH = '/v1/notes';
